/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCadastroRouteImport } from './routes/auth.cadastro'
import { Route as AppCursosRouteImport } from './routes/app.cursos'
import { Route as AppCursosIndexRouteImport } from './routes/app.cursos.index'
import { Route as AppCursosCursoIdRouteImport } from './routes/app.cursos.$cursoId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/auth/recuperar',
  path: '/auth/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/auth/cadastro',
  path: '/auth/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosIndexRoute = AppCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppCursosCursoIdRoute = AppCursosCursoIdRouteImport.update({
  id: '/$cursoId',
  path: '/$cursoId',
  getParentRoute: () => AppCursosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/app/': typeof AppIndexRoute
  '/app/cursos/$cursoId': typeof AppCursosCursoIdRoute
  '/app/cursos/': typeof AppCursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/app': typeof AppIndexRoute
  '/app/cursos/$cursoId': typeof AppCursosCursoIdRoute
  '/app/cursos': typeof AppCursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/app/': typeof AppIndexRoute
  '/app/cursos/$cursoId': typeof AppCursosCursoIdRoute
  '/app/cursos/': typeof AppCursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/cursos'
    | '/auth/cadastro'
    | '/auth/login'
    | '/auth/recuperar'
    | '/app/'
    | '/app/cursos/$cursoId'
    | '/app/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/cadastro'
    | '/auth/login'
    | '/auth/recuperar'
    | '/app'
    | '/app/cursos/$cursoId'
    | '/app/cursos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/cursos'
    | '/auth/cadastro'
    | '/auth/login'
    | '/auth/recuperar'
    | '/app/'
    | '/app/cursos/$cursoId'
    | '/app/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/auth/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/auth/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cursos': {
      id: '/app/cursos'
      path: '/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cursos/': {
      id: '/app/cursos/'
      path: '/'
      fullPath: '/app/cursos/'
      preLoaderRoute: typeof AppCursosIndexRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/cursos/$cursoId': {
      id: '/app/cursos/$cursoId'
      path: '/$cursoId'
      fullPath: '/app/cursos/$cursoId'
      preLoaderRoute: typeof AppCursosCursoIdRouteImport
      parentRoute: typeof AppCursosRoute
    }
  }
}

interface AppCursosRouteChildren {
  AppCursosCursoIdRoute: typeof AppCursosCursoIdRoute
  AppCursosIndexRoute: typeof AppCursosIndexRoute
}

const AppCursosRouteChildren: AppCursosRouteChildren = {
  AppCursosCursoIdRoute: AppCursosCursoIdRoute,
  AppCursosIndexRoute: AppCursosIndexRoute,
}

const AppCursosRouteWithChildren = AppCursosRoute._addFileChildren(
  AppCursosRouteChildren,
)

interface AppRouteChildren {
  AppCursosRoute: typeof AppCursosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCursosRoute: AppCursosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCadastroRoute: AuthCadastroRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
